# CMake generated Testfile for 
# Source directory: /home/dd/workspace/bake/source/ns-3.42/src/internet/examples
# Build directory: /home/dd/workspace/bake/source/ns-3.42/src/internet/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-main-simple "ns3.42-main-simple")
set_tests_properties(ctest-main-simple PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/internet/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/internet/examples/CMakeLists.txt;1;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/internet/examples/CMakeLists.txt;0;")
add_test(ctest-neighbor-cache-example "ns3.42-neighbor-cache-example")
set_tests_properties(ctest-neighbor-cache-example PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/internet/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/internet/examples/CMakeLists.txt;10;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/internet/examples/CMakeLists.txt;0;")
add_test(ctest-neighbor-cache-dynamic "ns3.42-neighbor-cache-dynamic")
set_tests_properties(ctest-neighbor-cache-dynamic PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/internet/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/internet/examples/CMakeLists.txt;20;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/internet/examples/CMakeLists.txt;0;")
