# CMake generated Testfile for 
# Source directory: /home/dd/workspace/bake/source/ns-3.42/src/internet-apps/examples
# Build directory: /home/dd/workspace/bake/source/ns-3.42/src/internet-apps/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dhcp-example "ns3.42-dhcp-example")
set_tests_properties(ctest-dhcp-example PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/internet-apps/examples/CMakeLists.txt;1;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/internet-apps/examples/CMakeLists.txt;0;")
add_test(ctest-traceroute-example "ns3.42-traceroute-example")
set_tests_properties(ctest-traceroute-example PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/internet-apps/examples/CMakeLists.txt;12;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/internet-apps/examples/CMakeLists.txt;0;")
add_test(ctest-ping-example "ns3.42-ping-example")
set_tests_properties(ctest-ping-example PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/internet-apps/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/internet-apps/examples/CMakeLists.txt;25;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/internet-apps/examples/CMakeLists.txt;0;")
