# CMake generated Testfile for 
# Source directory: /home/dd/workspace/bake/source/ns-3.42/src/click/examples
# Build directory: /home/dd/workspace/bake/source/ns-3.42/src/click/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-nsclick-simple-lan "ns3.42-nsclick-simple-lan")
set_tests_properties(ctest-nsclick-simple-lan PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/click/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;1;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;0;")
add_test(ctest-nsclick-raw-wlan "ns3.42-nsclick-raw-wlan")
set_tests_properties(ctest-nsclick-raw-wlan PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/click/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;11;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;0;")
add_test(ctest-nsclick-udp-client-server-csma "ns3.42-nsclick-udp-client-server-csma")
set_tests_properties(ctest-nsclick-udp-client-server-csma PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/click/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;21;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;0;")
add_test(ctest-nsclick-udp-client-server-wifi "ns3.42-nsclick-udp-client-server-wifi")
set_tests_properties(ctest-nsclick-udp-client-server-wifi PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/click/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;31;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;0;")
add_test(ctest-nsclick-routing "ns3.42-nsclick-routing")
set_tests_properties(ctest-nsclick-routing PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/click/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;41;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;0;")
add_test(ctest-nsclick-defines "ns3.42-nsclick-defines")
set_tests_properties(ctest-nsclick-defines PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/click/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;51;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/click/examples/CMakeLists.txt;0;")
