# CMake generated Testfile for 
# Source directory: /home/dd/workspace/bake/source/ns-3.42/src/wimax/examples
# Build directory: /home/dd/workspace/bake/source/ns-3.42/src/wimax/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-wimax-ipv4 "ns3.42-wimax-ipv4")
set_tests_properties(ctest-wimax-ipv4 PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/wimax/examples/CMakeLists.txt;1;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/wimax/examples/CMakeLists.txt;0;")
add_test(ctest-wimax-multicast "ns3.42-wimax-multicast")
set_tests_properties(ctest-wimax-multicast PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/wimax/examples/CMakeLists.txt;12;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/wimax/examples/CMakeLists.txt;0;")
add_test(ctest-wimax-simple "ns3.42-wimax-simple")
set_tests_properties(ctest-wimax-simple PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/wimax/examples/CMakeLists.txt;22;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/wimax/examples/CMakeLists.txt;0;")
