# CMake generated Testfile for 
# Source directory: /home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples
# Build directory: /home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-red-tests "ns3.42-red-tests")
set_tests_properties(ctest-red-tests PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;1;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-red-vs-ared "ns3.42-red-vs-ared")
set_tests_properties(ctest-red-vs-ared PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;12;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-adaptive-red-tests "ns3.42-adaptive-red-tests")
set_tests_properties(ctest-adaptive-red-tests PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;23;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-pfifo-vs-red "ns3.42-pfifo-vs-red")
set_tests_properties(ctest-pfifo-vs-red PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;34;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-codel-vs-pfifo-basic-test "ns3.42-codel-vs-pfifo-basic-test")
set_tests_properties(ctest-codel-vs-pfifo-basic-test PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;45;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-codel-vs-pfifo-asymmetric "ns3.42-codel-vs-pfifo-asymmetric")
set_tests_properties(ctest-codel-vs-pfifo-asymmetric PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;56;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-pie-example "ns3.42-pie-example")
set_tests_properties(ctest-pie-example PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;68;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-fqcodel-l4s-example "ns3.42-fqcodel-l4s-example")
set_tests_properties(ctest-fqcodel-l4s-example PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-module-macros.cmake;538;build_exec;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;79;build_lib_example;/home/dd/workspace/bake/source/ns-3.42/src/traffic-control/examples/CMakeLists.txt;0;")
