# CMake generated Testfile for 
# Source directory: /home/dd/workspace/bake/source/ns-3.42/examples/tcp
# Build directory: /home/dd/workspace/bake/source/ns-3.42/examples/tcp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tcp-large-transfer "ns3.42-tcp-large-transfer")
set_tests_properties(ctest-tcp-large-transfer PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;1;build_example;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-star-server "ns3.42-tcp-star-server")
set_tests_properties(ctest-tcp-star-server PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;10;build_example;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-star "ns3.42-star")
set_tests_properties(ctest-star PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;19;build_example;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-bbr-example "ns3.42-tcp-bbr-example")
set_tests_properties(ctest-tcp-bbr-example PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;30;build_example;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-bulk-send "ns3.42-tcp-bulk-send")
set_tests_properties(ctest-tcp-bulk-send PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;43;build_example;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-pcap-nanosec-example "ns3.42-tcp-pcap-nanosec-example")
set_tests_properties(ctest-tcp-pcap-nanosec-example PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;52;build_example;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-variants-comparison "ns3.42-tcp-variants-comparison")
set_tests_properties(ctest-tcp-variants-comparison PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;61;build_example;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-pacing "ns3.42-tcp-pacing")
set_tests_properties(ctest-tcp-pacing PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;71;build_example;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-linux-reno "ns3.42-tcp-linux-reno")
set_tests_properties(ctest-tcp-linux-reno PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;81;build_example;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-validation "ns3.42-tcp-validation")
set_tests_properties(ctest-tcp-validation PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;92;build_example;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-dctcp-example "ns3.42-dctcp-example")
set_tests_properties(ctest-dctcp-example PROPERTIES  WORKING_DIRECTORY "/home/dd/workspace/bake/source/ns-3.42/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dd/workspace/bake/source/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dd/workspace/bake/source/ns-3.42/build-support/macros-and-definitions.cmake;1424;build_exec;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;104;build_example;/home/dd/workspace/bake/source/ns-3.42/examples/tcp/CMakeLists.txt;0;")
